### ISSUE TITLE
CID 166 hydronephrosis mislabeled as cyst?

### ISSUE THREAD

**Issue by t-suzuki** [neheller/kits19#11] opened 2019-04-03 02:50 UTC
Dear organizers,
thank you for replying to issue #10 !

I found another suspicious ground truth CID=166, in which a water-value blob in the right kidney is labeled 0. When tracking the blob downwards, it looks like a part of the ureter, and thus it might be appropriate to exclude it from the "strict kidney" labeling. The cyst-like appearance might be a result of hydronephrosis instead of a parapelvic cyst.

![image](https://user-images.githubusercontent.com/4010133/55449047-f9669280-557e-11e9-93fe-e24d7a25865c.png)

Thank you in advance.

**Comment by neheller** [comment] 2019-04-03 14:21
In this case, the neither the radiologist nor surgeon mentioned hydro, but they didn't mention a parapelvic cyst either. On inspection, I agree that this looks like ureter and should be excluded, but I will check with a radiologist to be sure. 

Thanks for your contributions to the QA process!

**Comment by neheller** [comment] 2019-04-03 22:47
After consulting with an expert, I can confirm that this feature is ureter and should be excluded from the kidney label. I will take care of this prior to April 15.

**Comment by neheller** [comment] 2019-04-15 23:37
This has been addressed in the amended release.

**Closed by neheller** 2019-04-15 23:37 UTC
Labels: Label Error
